name: software_engineering_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_profile_picture: ^2.0.0
  image_picker: ^1.2.0
  image: ^4.0.17
  mongo_dart: ^0.10.5
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  haptic_feedback: ^0.5.1+1
  flutter_inset_shadow: ^2.0.3
  http: ^1.5.0
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/login_icon.png
    - assets/test_data.json
    - assets/default_user.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/login_icon.png"